server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: userservice
              uri: lb://userservice
              predicates:
                - Path=/userservice/**
              filters:
                - StripPrefix=1

            - id: productservice
              uri: lb://productservice
              predicates:
                - Path=/productservice/**
              filters:
                - StripPrefix=1
            - id: checkoutservice
              uri: lb://checkoutservice
              predicates:
                - Path=/checkoutservice/**
              filters:
                - name: Authenticate
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

