server:
  port: 8082
spring:
  application:
    name: checkoutservice
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/boozeproducts
  driver:
    class: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
        enabled: true
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
info:
  app:
    name: "checkoutservice"
    description: "checkout service microservice for buynbooze"
    version: "1.0.0"

Spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
